### ISSUE TITLE
Doesn't compile on stable rust

### ISSUE THREAD

**Issue by io12** [nixpulvis/brainfuck#29]
This currently requires nightly rust to build.

**Comment by nixpulvis** [comment]
@io12 I haven't been playing with this project much lately, however looking at it again now, I don't see the issue with stable Rust. However, it's not updated yet for 2018. I'll fix that momentarily. Similarly, the `#![deny(warnings)]` attribute is causing issues with a few new deprecations, which I will also solve here in a bit.

If these two fixes don't clear up your issue, please let me know what I'm missing, and I'll be happy to fix it.

:cherries:

**Comment by nixpulvis** [comment]
Updated. 9c6e8554cfe5691d631bcc8a290a53e68866f191 specifically makes the `stable` toolchain the default.

**Comment by io12** [comment]
Ok I looked into the issue a bit more and it seems like `master` compiles ok but the crates.io release is very old and doesn't anymore. A new crates.io release can fix this.

**Comment by nixpulvis** [comment]
@io12 I've released version 0.2.1 to crates.io. Thanks for pointing this out to me. I'm closing this issue, but let me know if you have any other issues.

:clinking_glasses:
